version: '3.2'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_test
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    restart: unless-stopped
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:5.4.3
    container_name: grafana_test
    ports:
      - 3000:3000
    volumes:
      - ./grafana/:/etc/grafana/provisioning/
    environment:
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

  nodejs:
    build: ./node
    container_name: node_test
    command: npm run start
    restart: unless-stopped
    volumes:
      - ./node:/node_app/
    ports:
      - 9229:9229
      - 3333:3333
